## ------------------ goal definition ------------------ ##

float32 move_x
# in meters

float32 move_y
# in meters

---

## ----------------- result definition ----------------- ##

bool goal_achieved		
# it is true if and only if the goal has been achieved

---

## ---------------- feedback definition ---------------- ##

float32 percentage			
# in range of 0% to 100%

float32 elapsed_time			
# in seconds

float32 expected_time		
# in seconds
